chore: fail tests build if tests fail due to reporting issues

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -240,12 +240,15 @@ jobs:
 
       - name: Run nextest
         shell: bash
+        id:
+          test
         env:
           RUSTC_BOOTSTRAP: 1
           RUSTFLAGS: "-Zinstrument-coverage"
           LLVM_PROFILE_FILE: "profiling/profile-%p-%m.profraw"
         run: |
           cargo nextest run --profile ci --no-fail-fast --all-targets --workspace
+          echo "TEST_FAILED=$?" >> ${GITHUB_ENV}
         continue-on-error: true
 
       - name: Upload test results
@@ -288,6 +291,16 @@ jobs:
         run: |
           ./cc-test-reporter format-coverage reports/lcov.info --input-type lcov --output reports/codeclimate.json
           ./cc-test-reporter upload-coverage --input reports/codeclimate.json
+
+      - name: Fail if tests failed
+        shell: bash
+        run: |
+          # the test reporter we use (or any for that matter)
+          # all show a report. But we cannot depend on that report because
+          # we don't know which subsection it belongs in GitHub
+          # so we explicitly fail this one
+          # which will fail All Done
+          exit ${TEST_FAILED}
 
   cargo-clippy-and-report:
     name: Cargo clippy (and report)
