tags is a list, so we're dumping it in output

diff --git a/.github/workflows/promote-artifacts.yml b/.github/workflows/promote-artifacts.yml
--- a/.github/workflows/promote-artifacts.yml
+++ b/.github/workflows/promote-artifacts.yml
@@ -70,6 +70,7 @@ jobs:
 
       - name: Find all tags for current "Add or retag the Docker container."
         shell: bash
+        id: tags
         run: |
 
           existing_tags=$(
@@ -81,59 +82,59 @@ jobs:
               ls ${FULL_IMAGE_NAME}
           )
 
-          echo "EXISTING_TAGS=${existing_tags}" >> ${GITHUB_ENV}
+          echo "::set-output name=existing-tags::${existing_tags}"
 
-      - name: Find out if the incoming PR has a docker image in the form of :pr-<number>
-        if: ${{ github.event_name == 'pull_request' }}
-        env:
-          PR_TAG: "pr-${{ github.event.number }}"
-        shell: bash
-        run: |
+      # - name: Find out if the incoming PR has a docker image in the form of :pr-<number>
+      #   if: ${{ github.event_name == 'pull_request' }}
+      #   env:
+      #     PR_TAG: "pr-${{ github.event.number }}"
+      #   shell: bash
+      #   run: |
 
-          # search for the tag
-          echo ${EXISTING_TAGS} | grep ${PR_TAG}
+      #     # search for the tag
+      #     echo ${EXISTING_TAGS} | grep ${PR_TAG}
 
-          if [ $? -eq 0 ]
-          then
-            echo "Incoming PR produced a Docker image"
-            echo "OLD_TAG=${PR_TAG}" >> ${GITHUB_ENV}
-          fi
+      #     if [ $? -eq 0 ]
+      #     then
+      #       echo "Incoming PR produced a Docker image"
+      #       echo "OLD_TAG=${PR_TAG}" >> ${GITHUB_ENV}
+      #     fi
 
-      - name: Find SHA suffix for retagging
-        if: ${{ env.OLD_TAG == '' }}
-        env:
-          SHA: ${{ github.event_name == 'pull_request' && github.pull_request.base.sha || github.sha }}
-        shell: bash
-        run: |
+      # - name: Find SHA suffix for retagging
+      #   if: ${{ env.OLD_TAG == '' }}
+      #   env:
+      #     SHA: ${{ github.event_name == 'pull_request' && github.pull_request.base.sha || github.sha }}
+      #   shell: bash
+      #   run: |
 
-          tag_prefix="sha-${SHA}-"
+      #     tag_prefix="sha-${SHA}-"
 
-          old_tag=$(echo ${EXISTING_TAGS} | grep --only-matching ${tag_prefix}-.*)
+      #     old_tag=$(echo ${EXISTING_TAGS} | grep --only-matching ${tag_prefix}-.*)
 
-          echo "OLD_TAG=${old_tag}" >> ${GITHUB_ENV}
+      #     echo "OLD_TAG=${old_tag}" >> ${GITHUB_ENV}
 
-      - name: Dump
-        shell: bash
-        run: |
-          echo ${{ github }}
+      # - name: Dump
+      #   shell: bash
+      #   run: |
+      #     echo ${{ github }}
 
-      - name: Actually re-tag the container
-        env:
-          NEW_TAG: ${{ github.event_name == 'pull_request' && 'pr-${{ github.event.number }}' || github.sha }}
-        shell: bash
-        run: |
+      # - name: Actually re-tag the container
+      #   env:
+      #     NEW_TAG: ${{ github.event_name == 'pull_request' && 'pr-${{ github.event.number }}' || github.sha }}
+      #   shell: bash
+      #   run: |
 
-          docker run \
-            --env DOCKER_CONFIG=${CRANE_DOCKER_CONFIG_LOCATION} \
-            --mount "${CRANE_DOCKER_CONFIG_VOLUME_MOUNT}" \
-            --rm \
-            gcr.io/go-containerregistry/crane:latest \
-            tag "${FULL_IMAGE_NAME}:${OLD_TAG}" ${NEW_TAG}
+      #     docker run \
+      #       --env DOCKER_CONFIG=${CRANE_DOCKER_CONFIG_LOCATION} \
+      #       --mount "${CRANE_DOCKER_CONFIG_VOLUME_MOUNT}" \
+      #       --rm \
+      #       gcr.io/go-containerregistry/crane:latest \
+      #       tag "${FULL_IMAGE_NAME}:${OLD_TAG}" ${NEW_TAG}
 
-      - name: Cleanup!
-        if: ${{ always() }}
-        shell: bash
-        run: |
-          docker volume rm ${{ env.CRANE_DOCKER_CONFIG_VOLUME }}
+      # - name: Cleanup!
+      #   if: ${{ always() }}
+      #   shell: bash
+      #   run: |
+      #     docker volume rm ${{ env.CRANE_DOCKER_CONFIG_VOLUME }}
 
 
